-- This copy is embedded by the database package. Keep it in sync with /migrations/001_initial.sql.
CREATE TABLE IF NOT EXISTS users (discord_user_id TEXT PRIMARY KEY, display_name TEXT NOT NULL DEFAULT '', timezone TEXT NOT NULL DEFAULT 'America/New_York', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS guilds (discord_guild_id TEXT PRIMARY KEY, timezone TEXT NOT NULL DEFAULT 'America/New_York', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reminders (id UUID PRIMARY KEY, title TEXT NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200), description TEXT NOT NULL DEFAULT '', creator_id TEXT NOT NULL, guild_id TEXT NOT NULL DEFAULT '', channel_id TEXT NOT NULL, mention_target TEXT NOT NULL, delivery_at TIMESTAMPTZ NOT NULL, timezone TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','processing','sent','completed','cancelled','failed')), attempts INTEGER NOT NULL DEFAULT 0, next_attempt_at TIMESTAMPTZ NOT NULL, last_error TEXT NOT NULL DEFAULT '', discord_message_id TEXT NOT NULL DEFAULT '', claimed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS reminders_due_idx ON reminders (next_attempt_at) WHERE status IN ('scheduled', 'processing');
CREATE INDEX IF NOT EXISTS reminders_creator_idx ON reminders (creator_id, delivery_at);
CREATE INDEX IF NOT EXISTS reminders_guild_idx ON reminders (guild_id, delivery_at);
CREATE TABLE IF NOT EXISTS reminder_deliveries (id BIGSERIAL PRIMARY KEY, reminder_id UUID NOT NULL REFERENCES reminders(id) ON DELETE CASCADE, idempotency_key TEXT NOT NULL UNIQUE, attempted_at TIMESTAMPTZ NOT NULL DEFAULT now(), discord_message_id TEXT NOT NULL DEFAULT '', result TEXT NOT NULL, error TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS conversations (id UUID PRIMARY KEY, guild_id TEXT NOT NULL DEFAULT '', channel_id TEXT NOT NULL, user_id TEXT NOT NULL, previous_response_id TEXT NOT NULL DEFAULT '', expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE (channel_id, user_id));
CREATE TABLE IF NOT EXISTS ai_tool_runs (id UUID PRIMARY KEY, user_id TEXT NOT NULL, channel_id TEXT NOT NULL, tool_name TEXT NOT NULL, arguments JSONB NOT NULL, result TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
